version: "3"
services:
  nginx:
    image: crunchgeek/nginx-pagespeed
    container_name: nginx
    hostname: nginx
    restart: always
    environment:
      NGINX_GEOIP: 'off'
      NGINX_PAGESPEED: 'on'
      NGINX_PAGESPEED_JS: 'on'
      NGINX_PAGESPEED_CSS: 'on'
      NGINX_PAGESPEED_IMG: 'on'
    ports:
      - "80:80"
      - "443:443"
    logging:
      options:
        max-file: "3"
        max-size: "50m"
    volumes:
      - "./apps/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./apps/nginx/includes:/etc/nginx/includes:ro"
      - "./apps/nginx/default:/etc/nginx/default:ro"
      - "./apps/nginx/vhosts:/etc/nginx/vhosts:ro"
      - "./apps/run:/var/run"
      - "./log:/var/log/nginx"
      - "./www/html:/var/www/html:ro"
#     - "./apps/certbot/tls/fullchain.pem:/etc/nginx/default/fullchain.pem:ro"
#     - "./apps/certbot/tls/private.pem:/etc/nginx/default/private.pem:ro"
  mysql:
    image: mariadb:10.5
    container_name: mysql
    hostname: mysql
    restart: always
    environment:
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD:
      MYSQL_ROOT_PASSWORD:
    logging:
      options:
        max-file: "10"
        max-size: "50m"
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 500M
    command:
      - mysqld
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - "./apps/mysql/my.cnf:/etc/mysql/my.cnf"
      - "./apps/mysql/db:/var/lib/mysql"
      - "./apps/run/mysqld:/var/run/mysqld:rw"
  php:
    image: synst/php:8.0
    container_name: php
    hostname: php
    restart: always
    logging:
      options:
        max-file: "10"
        max-size: "50m"
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 500M
    volumes:
      - "./apps/php/php.ini:/etc/php/8.0/fpm/php.ini:ro"
      - "./apps/php/www.conf:/etc/php/8.0/fpm/pool.d/www.conf:ro"
      - "./apps/php/php-fpm.conf:/etc/php/8.0/fpm/php-fpm.conf:ro"
      - "./apps/php/20-uploadprogress.ini:/etc/php/8.0/fpm/conf.d/20-uploadprogress.ini:ro"
      - "./apps/crontabs:/var/spool/cron/crontabs:rw"
      - "./apps/root/.ssh:/root/.ssh:ro"
      - "./apps/run/php:/var/run/php:rw"
      - "./apps/run/mysqld:/var/run/mysqld:rw"
      - "./www:/var/www:rw"
      - "./log/php:/var/log/php:rw"
